//start by getting the runs that completed, either by using the Completed or Failed status codes
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.DATAFACTORY"
| where Category == "ActivityRuns"
| where status_s == "Succeeded" or status_s == "Failed"
| project pipelineRunId_g, activityName_s, start_t, end_t, activityType_s, effectiveIntegrationRuntime_s, Output_executionDuration_d, Output_durationInQueue_integrationRuntimeQueue_d, Input_storedProcedureName_s, Input_storedProcedureParameters_at_enabled_value_s, Input_storedProcedureParameters_load_mode_value_s, DataProviderKey = Input_storedProcedureParameters_part_col1_val_value_s, TimePeriodEndDate = Input_storedProcedureParameters_part_col2_val_value_s, SourceTable = Input_storedProcedureParameters_src_table_value_s, SubjectArea = Input_storedProcedureParameters_subject_area_value_s 
| extend DurationMs = datetime_diff('millisecond', end_t, start_t), Duration_Min = datetime_diff('minute', end_t, start_t)
